#!/usr/bin/env python3
"""
ResumeTerminal - A high-end CLI resume generator with ATS optimization.
Bridges professional data with design tokens for executive-quality output.

Usage:
    python resume_terminal.py generate --data user_data.json
    python resume_terminal.py generate --data user_data.json --job job_description.txt
    python resume_terminal.py init
    python resume_terminal.py design
"""

import json
import os
import sys
import re
import string
import textwrap
from collections import Counter
from datetime import datetime
from pathlib import Path

import click
from reportlab.lib.pagesizes import letter
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from reportlab.lib.colors import HexColor, black, white
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, HRFlowable,
    KeepTogether, Table, TableStyle, KeepInFrame
)
from reportlab.lib.enums import TA_LEFT, TA_CENTER, TA_RIGHT

STITCH_TOKENS = {
    "meta": {
        "design_system_name": "Sovereign Executive",
        "design_system_id":   "assets/98dbdadafc8d46e690ac97f17bd1139b",
        "project_id":         "projects/9257336750068346884",
        "creative_north_star": "The Architectural Ledger",
        "version":            "1",
    },
    "palette": {
        "ink":         "#1A1A2E",
        "ink_light":   "#333333",
        "ink_muted":   "#444444",

        "rule":        "#1A1A2E",
        "accent":      "#3B82F6",
        "accent_soft": "#EFF6FF",

        "page":              "#F9F9F7",
        "surface":           "#FFFFFF",
        "surface_container": "#F9FAFB",
        "surface_high":      "#F3F4F6",
        "surface_highest":   "#E5E7EB",

        "secondary":         "#6B7280",
        "tertiary":          "#9CA3AF",
    },
    "typography": {

        "stitch_font":    "Inter",
        "font_primary":   "Helvetica",
        "font_bold":      "Helvetica-Bold",
        "font_oblique":   "Helvetica-Oblique",

        "size_name":      24,
        "size_title":     11,
        "size_section":   12,
        "size_body":      10,
        "size_small":     9,
        "leading_body":   15,
        "leading_tight":  14,
    },
    "spacing": {
        "margin_top":    0.60,
        "margin_bottom": 0.60,
        "margin_left":   0.65,
        "margin_right":  0.65,

        "section_gap":   14,
        "item_gap":      6,
    },
    "rules": {
        "single_column":    True,
        "text_layer_only":  True,
        "no_images":        True,
        "no_nested_tables": True,
        "no_line_borders":  True,
        "no_rounded_corners": True,
        "ats_safe":         True,
        "header_alignment": TA_CENTER,
        "header_uppercase": True,
        "contact_font":     "Helvetica",
    }
}

DESIGN_MD_TEMPLATE = """\

> Generated by ResumeTerminal | Stitch MCP Design Bridge
> Design System: Sovereign Executive (assets/98dbdadafc8d46e690ac97f17bd1139b)
> Project: projects/9257336750068346884

---

**The Architectural Ledger** - This design system moves away from the
"template" aesthetic of standard resumes, pivoting toward high-end
editorial precision. It treats the page not as a document to be filled,
but as a structured space to be curated.

By stripping away icons, graphics, and decorative lines, we rely entirely
on the tension between geometric typography and the vacuum of whitespace.
The result is a "brutalist executive" look - authoritative, unapologetically
sharp (0px radii), and optimized for both human elite-level recruiters
and ATS algorithms.

Principles:

1. **Legibility over decoration** - No icons, no color blocks, no sidebars.
2. **ATS transparency** - Text layer is always machine-readable.
3. **Typographic hierarchy** - Weight and size alone create structure.
4. **Architectural spacing** - Content framed like gallery art.

---

| Token              | Hex       | Stitch Source            | Usage                         |
|--------------------|-----------|--------------------------|-------------------------------|
| `ink`              | `
| `ink_light`        | `
| `ink_muted`        | `
| `rule`             | `
| `accent`           | `
| `accent_soft`      | `
| `page`             | `
| `surface`          | `
| `surface_high`     | `
| `secondary`        | `

Key rule: Deep navy (#1A1A2E) replaces pure black. It commands more
authority while being softer on the eye, paired with off-white (#F9F9F7)
that feels more like premium stationery than a digital screen.

---

Stitch specifies Inter; Helvetica serves as the ATS-safe PDF fallback.

| Role             | Font              | Size | Leading | Stitch Role  |
|------------------|-------------------|------|---------|--------------|
| Candidate Name   | Helvetica-Bold    | 24pt | 30pt    | display-md   |
| Current Title    | Helvetica-Oblique | 10pt | 13pt    | title-md     |
| Section Header   | Helvetica-Bold    | 9pt  | 11pt    | headline-sm  |
| Body / Bullets   | Helvetica         | 9pt  | 13pt    | body-md      |
| Metadata / Dates | Helvetica-Oblique | 8pt  | 11pt    | label-sm     |

Hierarchy via Weight: Use weight (Medium vs Regular) and scale to ensure
the machine parses headers correctly while the human sees a curated hierarchy.

---

The Architectural Ledger uses NO line borders for sectioning.
Boundaries are defined by whitespace and tonal shifts.

```
+---------------------------------------------------+
|                                                   |
|  CANDIDATE NAME                                   |
|  Current Role  |  Location                        |
|  email | phone | linkedin | github                |
|                                                   |
|  PROFESSIONAL SUMMARY                             |
|  [2-3 sentence elevator pitch]                    |
|                                                   |
|  EXPERIENCE                                       |
|  Company Name                      Month Year -   |
|  Job Title  |  Location            Month Year     |
|  * Achievement bullet (metric-led)                |
|  * Achievement bullet (metric-led)                |
|                                                   |
|  PROJECTS                                         |
|  Project Name                      Link           |
|  Tech: skill1, skill2                             |
|  * Project result/impact                          |
|                                                   |
|  EDUCATION                                        |
|  Institution                       Year           |
|  Degree, Field                                    |
|                                                   |
|  SKILLS                                           |
|  Category: [skillA, skillB, skillC]               |
+---------------------------------------------------+
```

- **Single column only** - no multi-column floats or text boxes.
- **No images or icons** - the Ledger relies on the purity of the typeface.
- **No nested tables** - flat structure only.
- **0px rounded corners** - executive precision.
- Margins: 0.80in left/right, 0.75in top/bottom (gallery framing).
- Page size: US Letter (8.5 x 11 in).

---

| Rule                          | Status      |
|-------------------------------|-------------|
| Single-column layout          | Required    |
| Text layer (no scanned image) | Required    |
| Standard section labels       | Required    |
| No icons / SVG                | Required    |
| No tables for structure       | Required    |
| Unicode bullets only (*)      | Required    |
| Date format: Mon YYYY         | Required    |
| Contact on page 1             | Required    |

---

When a job description is supplied via `--job`:

1. Strip stop-words and punctuation from JD.
2. Rank remaining tokens by term frequency.
3. Cross-reference against resume content.
4. Surface **gap keywords** - present in JD but absent from resume.
5. Suggest contextual placement per section.

**Target density:** 60-75% keyword overlap with JD for ATS scoring.

---

Scaled from Stitch web tokens to print:

| Context          | Web (px) | Print (pt) | Usage                     |
|------------------|----------|------------|---------------------------|
| Section Spacing  | 64px     | 14pt       | Between major sections    |
| Group Spacing    | 32px     | 7pt        | Title to description      |
| Inline Spacing   | 16px     | 4pt        | Paragraph to paragraph    |
| Page Margins     | 80px     | 0.80in     | Gallery art framing       |

---

*Generated by ResumeTerminal Stitch MCP bridge.*
*Design System: Sovereign Executive v1 (The Architectural Ledger)*
*Modify tokens in `STITCH_TOKENS` inside `resume_terminal.py`.*
"""

SAMPLE_USER_DATA = {
    "personal": {
        "name": "Alexandra Chen",
        "title": "Senior Product Manager",
        "email": "a.chen@email.com",
        "phone": "+1 (415) 555-0192",
        "location": "San Francisco, CA",
        "linkedin": "linkedin.com/in/alexandrachen",
        "github": "github.com/achen"
    },
    "summary": "Results-driven Senior Product Manager with 8+ years driving 0→1 product launches at hyper-growth SaaS companies. Led cross-functional teams of 20+ to ship features used by 5M+ users, consistently delivering 30%+ YoY revenue growth. Expert in data-driven roadmap prioritization, OKR frameworks, and stakeholder alignment at the C-suite level.",
    "experience": [
        {
            "company": "Vertex Systems",
            "title": "Senior Product Manager",
            "location": "San Francisco, CA",
            "start": "Jan 2021",
            "end": "Present",
            "bullets": [
                "Spearheaded launch of AI-powered analytics dashboard, driving 42% increase in DAU within 90 days of release.",
                "Managed $4.2M product budget and roadmap across 3 engineering squads (18 engineers), delivering 6 major releases on schedule.",
                "Defined and executed go-to-market strategy for enterprise tier, closing $8M ARR in year one."
            ]
        }
    ],
    "projects": [
        {
            "name": "CloudGuard - Open Source Security Scanner",
            "link": "github.com/alex/cloudguard",
            "tech": "Python, Docker, AWS Lambda",
            "bullets": [
                "Developed an automated vulnerability scanner for AWS infrastructure reaching 500+ stars on GitHub.",
                "Integrated real-time threat detection using AWS SDK, reducing scan times by 65%.",
                "Implemented detailed JSON reporting and Slack notifications for engineering teams."
            ]
        },
        {
            "name": "AI-Powered Task Orchestrator",
            "link": "orchestrator.ai",
            "tech": "Next.js, OpenAI API, PostgreSQL",
            "bullets": [
                "Built a natural language task manager that automates project scheduling for small teams.",
                "Optimized database queries decreasing page load times from 2.4s to 400ms."
            ]
        }
    ],
    "education": [
        {
            "institution": "Stanford University",
            "degree": "M.S. Computer Science",
            "field": "Human-Computer Interaction",
            "year": "2016"
        },
        {
            "institution": "UC Berkeley",
            "degree": "B.S. Electrical Engineering & Computer Science",
            "field": "",
            "year": "2014"
        }
    ],
    "skills": {
        "Product": ["Roadmapping", "OKRs", "A/B Testing", "User Research", "PRD Writing"],
        "Technical": ["SQL", "Python", "Figma", "Looker", "JIRA", "Amplitude"],
        "Leadership": ["Cross-functional Teams", "Stakeholder Management", "Executive Presentations"],
        "Methodologies": ["Agile", "Scrum", "Design Thinking", "Lean Startup"]
    },
    "certifications": [
        {"name": "AWS Certified Solutions Architect", "issuer": "Amazon Web Services", "year": "2023"},
        {"name": "Professional Scrum Master I", "issuer": "Scrum.org", "year": "2022"}
    ]
}

STOP_WORDS = {
    "a","an","the","and","or","but","in","on","at","to","for","of","with",
    "by","from","is","are","was","were","be","been","being","have","has",
    "had","do","does","did","will","would","could","should","may","might",
    "shall","can","need","dare","ought","used","it","its","this","that",
    "these","those","i","we","you","he","she","they","me","us","him","her",
    "them","my","our","your","his","our","their","what","which","who","whom",
    "as","if","then","than","so","yet","both","either","neither","not","no",
    "nor","also","just","more","most","other","such","only","own","same",
    "too","very","about","above","after","again","against","all","any",
    "because","before","between","during","each","few","further","here",
    "how","into","must","now","once","only","other","out","over","same",
    "some","such","through","under","until","up","very","while","why","per",
    "within","without","across","along","around","behind","below","beside",
    "besides","beyond","down","since","toward","upon","within","would","work"
}

def extract_keywords(text: str, top_n: int = 40) -> list[tuple[str, int]]:
    """Extract high-frequency non-stop keywords from text."""
    text = text.lower()
    text = re.sub(r'[^\w\s+#]', ' ', text)
    tokens = text.split()
    tokens = [t for t in tokens if len(t) > 2 and t not in STOP_WORDS]

    freq = Counter(tokens)
    return freq.most_common(top_n)

def analyze_ats_gaps(user_data: dict, jd_text: str) -> dict:
    """Compare JD keywords vs resume content to find ATS gaps."""

    resume_parts = []
    resume_parts.append(user_data.get("summary", ""))
    for exp in user_data.get("experience", []):
        resume_parts.append(exp.get("title", ""))
        resume_parts.append(exp.get("company", ""))
        resume_parts.extend(exp.get("bullets", []))
    for proj in user_data.get("projects", []):
        resume_parts.append(proj.get("name", ""))
        resume_parts.append(proj.get("tech", ""))
        resume_parts.extend(proj.get("bullets", []))
    for edu in user_data.get("education", []): 
        resume_parts.append(edu.get("degree", ""))
        resume_parts.append(edu.get("field", ""))
    for cat, skills in user_data.get("skills", {}).items():
        resume_parts.extend(skills)

    resume_text = " ".join(resume_parts).lower()
    resume_words = set(resume_text.split())

    jd_keywords = extract_keywords(jd_text, top_n=50)
    gap_keywords = []
    present_keywords = []

    for kw, freq in jd_keywords:

        found = kw in resume_words or any(
            kw in w or w in kw for w in resume_words if len(w) > 3
        )
        if found:
            present_keywords.append((kw, freq))
        else:
            gap_keywords.append((kw, freq))

    coverage = len(present_keywords) / max(len(jd_keywords), 1) * 100
    return {
        "jd_top_keywords": jd_keywords[:20],
        "gap_keywords": gap_keywords[:15],
        "present_keywords": present_keywords[:15],
        "coverage_pct": round(coverage, 1),
        "top_gaps": [k for k, _ in gap_keywords[:8]]
    }

def draw_background(canvas, doc):
    """Draw the warm matte paper background for every page."""
    canvas.saveState()
    canvas.setFillColor(HexColor(STITCH_TOKENS["palette"]["page"]))
    canvas.rect(0, 0, letter[0], letter[1], fill=1, stroke=0)

    # Paint the right sidebar for two-column templates
    if not STITCH_TOKENS["rules"].get("single_column"):
        S = STITCH_TOKENS["spacing"]
        content_width = letter[0] - S["margin_left"] * inch - S["margin_right"] * inch
        right_col_x = S["margin_left"] * inch + content_width * 0.62
        canvas.setFillColor(HexColor("#D6E4EC"))
        canvas.rect(right_col_x, 0, letter[0] - right_col_x, letter[1], fill=1, stroke=0)

    canvas.restoreState()

def build_styles():
    """Build Stitch-token-derived paragraph styles."""
    T = STITCH_TOKENS["typography"]
    P = STITCH_TOKENS["palette"]
    styles = {}

    def c(hex_val):
        return HexColor(hex_val)

    styles["name"] = ParagraphStyle(
        "name",
        fontName=T["font_bold"],
        fontSize=T["size_name"],
        leading=30,
        textColor=c(P["ink"]),
        spaceAfter=2,
        alignment=STITCH_TOKENS["rules"].get("header_alignment", TA_CENTER),
    )
    styles["tagline"] = ParagraphStyle(
        "tagline",
        fontName=T["font_oblique"],
        fontSize=T["size_title"],
        leading=T["leading_tight"],
        textColor=c(P["ink_muted"]),
        spaceAfter=3,
        alignment=STITCH_TOKENS["rules"].get("header_alignment", TA_CENTER),
    )
    styles["contact"] = ParagraphStyle(
        "contact",
        fontName=STITCH_TOKENS["rules"].get("contact_font", T["font_primary"]),
        fontSize=9,
        leading=12,
        textColor=c(P["ink_muted"]),
        alignment=STITCH_TOKENS["rules"].get("header_alignment", TA_CENTER),
    )
    styles["section_label"] = ParagraphStyle(
        "section_label",
        fontName=T["font_bold"],
        fontSize=T["size_section"],
        leading=T["leading_tight"],
        textColor=c(P["ink"]),
        spaceBefore=12,
        spaceAfter=12,
        textTransform="uppercase",
        letterSpacing=1.5,
    )

    styles["company"] = ParagraphStyle(
        "company",
        fontName=T["font_bold"],
        fontSize=T["size_body"],
        leading=T["leading_tight"],
        textColor=c(P["ink"]),
    )
    styles["job_title"] = ParagraphStyle(
        "job_title",
        fontName=T["font_oblique"],
        fontSize=T["size_body"],
        leading=T["leading_tight"],
        textColor=c(P["ink_light"]),
        spaceAfter=3,
    )
    styles["date_line"] = ParagraphStyle(
        "date_line",
        fontName=T["font_oblique"],
        fontSize=T["size_small"],
        leading=T["leading_tight"],
        textColor=c(P["ink_muted"]),
        alignment=TA_RIGHT,
    )
    styles["bullet"] = ParagraphStyle(
        "bullet",
        fontName=T["font_primary"],
        fontSize=T["size_body"],
        leading=T["leading_body"],
        textColor=c(P["ink_light"]),
        leftIndent=12,
        bulletIndent=0,
        spaceAfter=2,
    )
    styles["body"] = ParagraphStyle(
        "body",
        fontName=T["font_primary"],
        fontSize=T["size_body"],
        leading=T["leading_body"],
        textColor=c(P["ink_light"]),
        spaceAfter=4,
    )
    styles["skills_cat"] = ParagraphStyle(
        "skills_cat",
        fontName=T["font_bold"],
        fontSize=T["size_body"],
        leading=T["leading_tight"],
        textColor=c(P["ink"]),
    )
    styles["skills_val"] = ParagraphStyle(
        "skills_val",
        fontName=T["font_primary"],
        fontSize=T["size_body"],
        leading=T["leading_body"],
        textColor=c(P["ink_light"]),
        spaceAfter=3,
    )
    styles["cert_name"] = ParagraphStyle(
        "cert_name",
        fontName=T["font_bold"],
        fontSize=T["size_body"],
        leading=T["leading_tight"],
        textColor=c(P["ink"]),
    )
    styles["cert_meta"] = ParagraphStyle(
        "cert_meta",
        fontName=T["font_primary"],
        fontSize=T["size_small"],
        leading=T["leading_tight"],
        textColor=c(P["ink_muted"]),
        spaceAfter=3,
    )
    return styles

def section_rule(story):
    """Add a horizontal rule under section header."""
    thickness = 1.5 if not STITCH_TOKENS["rules"].get("single_column") else 0.5
    story.append(HRFlowable(
        width="99%",
        thickness=thickness,
        color=HexColor(STITCH_TOKENS["palette"]["rule"]),
        spaceAfter=5,
        spaceBefore=1,
    ))

def section_header(story, title, styles):
    """Add a section header with clean dividers."""
    story.append(Spacer(1, STITCH_TOKENS["spacing"]["section_gap"]))

    story.append(Paragraph(title.upper(), styles["section_label"]))
    section_rule(story)

def apply_template(template_name: str):
    """Mutate STITCH_TOKENS globally to apply a specific template design."""
    P = STITCH_TOKENS["palette"]
    T = STITCH_TOKENS["typography"]
    R = STITCH_TOKENS["rules"]

    # Default: Sovereign Executive
    P["page"] = "#F9F9F7"
    P["ink"] = "#1A1A2E"
    P["ink_light"] = "#333333"
    P["ink_muted"] = "#444444"
    P["rule"] = "#1A1A2E"
    
    T["font_primary"] = "Helvetica"
    T["font_bold"] = "Helvetica-Bold"
    T["font_oblique"] = "Helvetica-Oblique"
    
    R["header_alignment"] = TA_CENTER
    R["header_uppercase"] = True
    R["contact_font"] = "Helvetica"

def build_pdf(user_data: dict, output_path: str, ats_report: dict | None = None):
    """Render the resume PDF using Stitch design tokens."""
    apply_template(user_data.get("template", "Sovereign Executive"))
    
    S = STITCH_TOKENS["spacing"]
    T = STITCH_TOKENS["typography"]
    styles = build_styles()
    P = STITCH_TOKENS["palette"]
    R = STITCH_TOKENS["rules"]

    personal = user_data.get("personal") or user_data.get("personal_info") or user_data.get("personalInfo") or user_data.get("Personal Info") or user_data
    name = personal.get("name") or user_data.get("name", "Candidate")

    doc = SimpleDocTemplate(
        output_path,
        pagesize=letter,
        topMargin=S["margin_top"] * inch,
        bottomMargin=S["margin_bottom"] * inch,
        leftMargin=S["margin_left"] * inch,
        rightMargin=S["margin_right"] * inch,
        title=f"Resume - {name}",
        author=name,
        subject="Professional Resume",
        creator="Cloak Resume Builder"
    )

    story = []

    name_str = name.upper() if R.get("header_uppercase") else name
    story.append(Paragraph(name_str, styles["name"]))
    
    title_str = personal.get('title', '')
    if title_str and R.get("header_uppercase"): title_str = title_str.upper()
    
    if not R.get("single_column"):
        # For Creative Bold, show title below name without location
        story.append(Paragraph(title_str, styles["tagline"]))
        story.append(Spacer(1, 4))
        story.append(HRFlowable(width="100%", thickness=1.5, color=HexColor(P["ink"]), spaceBefore=2, spaceAfter=8))
        
        # Build contact grid
        contact_parts = []
        
        def _fmt_contact(char, text):
            return f"<font backColor='#1A2639' color='white'>&nbsp;<b>{char}</b>&nbsp;</font> {text}"
            
        if personal.get("phone"): contact_parts.append(_fmt_contact("P", personal.get("phone")))
        if personal.get("email"): contact_parts.append(_fmt_contact("E", personal.get("email")))
        if personal.get("location"): contact_parts.append(_fmt_contact("A", personal.get("location")))
        if personal.get("linkedin"): contact_parts.append(_fmt_contact("W", personal.get("linkedin")))
        
        contact_line = " &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; ".join(contact_parts)
        story.append(Paragraph(contact_line, styles["contact"]))
        story.append(Spacer(1, 6))
        story.append(HRFlowable(width="100%", thickness=2, color=HexColor("#C4D6E0"), spaceBefore=2, spaceAfter=12))
    else:
        story.append(Paragraph(
            f"{title_str}  ·  {personal.get('location', '')}",
            styles["tagline"]
        ))
        contact_line = "  ·  ".join(filter(None, [
            personal.get("email", ""),
            personal.get("phone", ""),
            personal.get("linkedin", ""),
            personal.get("github", ""),
        ]))
        story.append(Paragraph(contact_line, styles["contact"]))
        story.append(HRFlowable(
            width="100%", thickness=1,
            color=HexColor(P["ink"]),
            spaceBefore=6, spaceAfter=0,
        ))

    left_column = []
    right_column = []
    
    def add_to_flow(block, target="left"):
        if R.get("single_column"):
            story.append(KeepTogether(block))
        else:
            if target == "left":
                left_column.extend(block)
            else:
                right_column.extend(block)

    if user_data.get("summary"):
        summary_block = []
        section_header(summary_block, "Objective" if not R.get("single_column") else "Professional Summary", styles)
        summary_block.append(Paragraph(user_data["summary"], styles["body"]))
        summary_block.append(Spacer(1, 8))
        add_to_flow(summary_block, "left")

    if user_data.get("projects"):
        for i, proj in enumerate(user_data["projects"]):
            entry_block = []
            if i == 0:
                section_header(entry_block, "Projects", styles)

            link_str = proj.get("link", "")
            tbl = Table(
                [[Paragraph(proj.get("name", ""), styles["company"]),
                  Paragraph(link_str, styles["date_line"])]],
                colWidths=["60%", "40%"],
                style=TableStyle([
                    ("VALIGN", (0, 0), (-1, -1), "TOP"),
                    ("LEFTPADDING", (0, 0), (-1, -1), 0),
                    ("RIGHTPADDING", (0, 0), (-1, -1), 0),
                    ("TOPPADDING", (0, 0), (-1, -1), 0),
                    ("BOTTOMPADDING", (0, 0), (-1, -1), 1),
                ])
            )
            entry_block.append(tbl)
            if proj.get("tech"):
                entry_block.append(Paragraph(f"<b>Tech:</b> {proj['tech']}", styles["job_title"]))
            for bullet in proj.get("bullets", []):
                entry_block.append(Paragraph(f"• {bullet}", styles["bullet"]))
            entry_block.append(Spacer(1, S["item_gap"]))
            add_to_flow(entry_block, "left")

    if user_data.get("experience"):
        for i, exp in enumerate(user_data["experience"]):
            entry_block = []
            if i == 0:
                section_header(entry_block, "Experience", styles)
            end_str = exp.get("end", "Present")
            date_str = f"{exp.get('start', '')} - {end_str}"
            loc_str  = exp.get("location", "")

            tbl = Table(
                [[Paragraph(exp.get("company", ""), styles["company"]),
                  Paragraph(date_str, styles["date_line"])]],
                colWidths=["70%", "30%"],
                style=TableStyle([
                    ("VALIGN", (0, 0), (-1, -1), "TOP"),
                    ("LEFTPADDING", (0, 0), (-1, -1), 0),
                    ("RIGHTPADDING", (0, 0), (-1, -1), 0),
                    ("TOPPADDING", (0, 0), (-1, -1), 0),
                    ("BOTTOMPADDING", (0, 0), (-1, -1), 1),
                ])
            )
            entry_block.append(tbl)
            title_val = exp.get("title") or exp.get("role") or ""
            title_loc = str(title_val)
            if loc_str:
                if title_loc:
                    title_loc += f"  •  {loc_str}"
                else:
                    title_loc = str(loc_str)
            entry_block.append(Paragraph(title_loc, styles["job_title"]))
            for bullet in exp.get("bullets", []):
                entry_block.append(Paragraph(f"• {bullet}", styles["bullet"]))
            entry_block.append(Spacer(1, S["item_gap"]))
            add_to_flow(entry_block, "left")

    if user_data.get("education"):
        edu_block = []
        section_header(edu_block, "Education", styles)
        for edu in user_data["education"]:
            parts = []
            if edu.get("degree"):
                parts.append(str(edu["degree"]))
            if edu.get("field"):
                parts.append(str(edu["field"]))
            degree_field = ", ".join(parts)
            if edu.get("percentage"):
                if degree_field:
                    degree_field += f"  •  {edu['percentage']}"
                else:
                    degree_field = str(edu["percentage"])
            
            if R.get("single_column"):
                tbl = Table(
                    [[Paragraph(edu.get("institution", ""), styles["company"]),
                      Paragraph(edu.get("year", ""), styles["date_line"])]],
                    colWidths=["70%", "30%"],
                    style=TableStyle([
                        ("VALIGN", (0, 0), (-1, -1), "TOP"),
                        ("LEFTPADDING", (0, 0), (-1, -1), 0),("RIGHTPADDING", (0, 0), (-1, -1), 0),
                        ("TOPPADDING", (0, 0), (-1, -1), 0),("BOTTOMPADDING", (0, 0), (-1, -1), 1),
                    ])
                )
                edu_block.append(tbl)
                if degree_field:
                    edu_block.append(Paragraph(degree_field, styles["job_title"]))
            else:
                # Year right-aligned, then institution + degree below
                year_str = edu.get("year", "")
                if year_str:
                    edu_block.append(Spacer(1, 4))
                    edu_block.append(Paragraph(year_str, ParagraphStyle(
                        "edu_year", fontName=T["font_bold"], fontSize=9,
                        textColor=HexColor(P["ink"]), alignment=TA_RIGHT,
                    )))
                    edu_block.append(HRFlowable(width="99%", thickness=0.5, color=HexColor(P["rule"]), spaceAfter=3, spaceBefore=1))
                edu_block.append(Paragraph(f"<b>{edu.get('institution', '')}</b>", styles["body"]))
                if degree_field:
                    edu_block.append(Paragraph(degree_field, styles["job_title"]))
                
                # Show location if available
                loc = edu.get("location", "")
                if loc:
                    edu_block.append(Spacer(1, 4))
                    edu_block.append(Paragraph(loc, styles["body"]))
                
            edu_block.append(Spacer(1, S["item_gap"] + 2))
        add_to_flow(edu_block, "right")

    if user_data.get("skills"):
        skills_block = []
        section_header(skills_block, "Key Skills" if not R.get("single_column") else "Skills", styles)
        if R.get("single_column"):
            for category, skill_list in user_data["skills"].items():
                skills_str = " • ".join(skill_list)
                skills_block.append(Paragraph(f'<b>{category}:</b>  {skills_str}', styles["skills_val"]))
        else:
            # For two-column: render each skill as individual bullet
            skill_style = ParagraphStyle(
                "skill_bullet", fontName=T["font_primary"],
                fontSize=8.5, leading=11,
                textColor=HexColor(P["ink_light"]),
            )
            for category, skill_list in user_data["skills"].items():
                # Category as a label
                skills_block.append(Paragraph(f'<b>• {category}:</b> {" • ".join(skill_list)}', skill_style))
        add_to_flow(skills_block, "right")

    if user_data.get("certifications"):
        cert_block = []
        section_header(cert_block, "Certifications", styles)
        for cert in user_data["certifications"]:
            if R.get("single_column"):
                tbl = Table(
                    [[Paragraph(cert.get("name", ""), styles["cert_name"]),
                      Paragraph(cert.get("year", ""), styles["date_line"])]],
                    colWidths=["70%", "30%"],
                    style=TableStyle([
                        ("VALIGN", (0, 0), (-1, -1), "TOP"),
                        ("LEFTPADDING", (0, 0), (-1, -1), 0),("RIGHTPADDING", (0, 0), (-1, -1), 0),
                        ("TOPPADDING", (0, 0), (-1, -1), 0),("BOTTOMPADDING", (0, 0), (-1, -1), 1),
                    ])
                )
                cert_block.append(tbl)
            else:
                cert_block.append(Paragraph(cert.get("year", ""), styles["date_line"]))
                cert_block.append(Paragraph(cert.get("name", ""), styles["cert_name"]))
            cert_block.append(Paragraph(cert.get("issuer", ""), styles["cert_meta"]))
        add_to_flow(cert_block, "right")

    if not R.get("single_column"):
        content_width = letter[0] - S["margin_left"] * inch - S["margin_right"] * inch
        col_ratio = 0.62
        left_col_width = content_width * col_ratio
        right_col_width = content_width * (1 - col_ratio)
        
        main_table = Table([[left_column, right_column]], colWidths=[left_col_width, right_col_width])
        main_table.setStyle(TableStyle([
            ('VALIGN', (0,0), (-1,-1), 'TOP'),
            ('LEFTPADDING', (1,0), (1,0), 14),
            ('RIGHTPADDING', (1,0), (1,0), 8),
            ('TOPPADDING', (1,0), (1,0), 6),
            ('BOTTOMPADDING', (1,0), (1,0), 0),
            ('LEFTPADDING', (0,0), (0,0), 0),
            ('RIGHTPADDING', (0,0), (0,0), 14),
            ('TOPPADDING', (0,0), (0,0), 0),
            ('BOTTOMPADDING', (0,0), (0,0), 0),
        ]))
        
        story.append(main_table)

    try:
        doc.build(story, onFirstPage=draw_background, onLaterPages=draw_background)
    except Exception as e:
        if "too large" in str(e).lower() and not R.get("single_column"):
            print(f"[Layout Fallback] Resume too long for 2-column layout. Switching to single column.")
            STITCH_TOKENS["rules"]["single_column"] = True
            return build_pdf(user_data, output_path, ats_report)
        else:
            raise

@click.group()
@click.version_option(version="1.0.0", prog_name="ResumeTerminal")
def cli():
    """
    ╔══════════════════════════════════════════╗
    ║       ResumeTerminal  v1.0.0             ║
    ║  High-End CLI Resume Generator           ║
    ║  Stitch MCP Design Bridge • ATS Engine   ║
    ╚══════════════════════════════════════════╝
    """
    pass

@cli.command()
def init():
    """Scaffold a sample user_data.json and DESIGN.md in the current directory."""
    _print_banner()
    json_path = Path("user_data.json")
    if json_path.exists():
        click.confirm(
            click.style("⚠  user_data.json already exists. Overwrite?", fg="yellow"),
            abort=True
        )
    json_path.write_text(json.dumps(SAMPLE_USER_DATA, indent=2))
    click.echo(click.style("✓  Created user_data.json", fg="green"))

    design_path = Path("DESIGN.md")
    design_path.write_text(DESIGN_MD_TEMPLATE, encoding="utf-8")
    click.echo(click.style("✓  Created DESIGN.md", fg="green"))
    click.echo()
    click.echo("  Edit user_data.json with your details, then run:")
    click.echo(click.style("  python resume_terminal.py generate --data user_data.json", fg="cyan"))

@cli.command()
def design():
    """Write the Stitch MCP DESIGN.md token file to the current directory."""
    _print_banner()
    path = Path("DESIGN.md")
    path.write_text(DESIGN_MD_TEMPLATE, encoding="utf-8")
    click.echo(click.style("✓  DESIGN.md written (Stitch Aesthetic v1)", fg="green"))
    click.echo(f"   Path: {path.resolve()}")

@cli.command()
@click.option("--data",   "-d", required=True,   type=click.Path(exists=True), help="Path to user_data.json")
@click.option("--job",    "-j", default=None,     type=click.Path(exists=True), help="Path to job description .txt for ATS analysis")
@click.option("--output", "-o", default=None,     type=str,                     help="Output PDF filename (default: <name>_resume.pdf)")
@click.option("--verbose","-v", is_flag=True,     default=False,                help="Print ATS keyword report to terminal")
def generate(data, job, output, verbose):
    """Generate a high-end executive resume PDF from user_data.json."""
    _print_banner()

    click.echo(click.style("  Loading profile data...", fg="cyan"))
    with open(data) as f:
        user_data = json.load(f)
    name = user_data.get("personal", {}).get("name", "resume")
    click.echo(f"  Candidate : {click.style(name, bold=True)}")

    click.echo(click.style("\n  [Stitch MCP] Fetching design tokens...", fg="blue"))
    _simulate_stitch_handshake()
    click.echo(click.style("  [Stitch MCP] ✓ Tokens loaded — Sovereign Executive (Architectural Ledger)", fg="green"))

    ats_report = None
    if job:
        click.echo(click.style("\n  [ATS Engine] Analyzing job description...", fg="blue"))
        with open(job) as f:
            jd_text = f.read()
        ats_report = analyze_ats_gaps(user_data, jd_text)
        _print_ats_report(ats_report, verbose)

    design_path = Path("DESIGN.md")
    if not design_path.exists():
        design_path.write_text(DESIGN_MD_TEMPLATE, encoding="utf-8")
        click.echo(click.style("  ✓  DESIGN.md created", fg="green"))

    if not output:
        slug = re.sub(r'[^a-zA-Z0-9]', '_', name).lower()
        output = f"{slug}_resume.pdf"
    click.echo(click.style(f"\n  [PDF] Rendering {output}...", fg="blue"))
    build_pdf(user_data, output, ats_report)
    click.echo(click.style(f"  ✓  PDF written → {Path(output).resolve()}", fg="green"))

    click.echo()
    _print_summary_box(output, ats_report)

def _print_banner():
    click.echo()
    click.echo(click.style("  ┌─────────────────────────────────────────┐", fg="bright_black"))
    click.echo(click.style("  │  ", fg="bright_black") +
               click.style("ResumeTerminal", bold=True, fg="white") +
               click.style("  ·  Stitch MCP Edition         │", fg="bright_black"))
    click.echo(click.style("  └─────────────────────────────────────────┘", fg="bright_black"))
    click.echo()

def _simulate_stitch_handshake():
    """Display Stitch MCP design-system metadata from actual Sovereign Executive tokens."""
    import time
    meta = STITCH_TOKENS["meta"]
    steps = [
        f"  Stitch MCP  |  Design System: {meta['design_system_name']}",
        f"  Asset ID    :  {meta['design_system_id']}",
        f"  Project     :  {meta['project_id']}",
        f"  North Star  :  {meta['creative_north_star']}",
        f"  Version     :  {meta['version']}",
    ]
    for step in steps:
        click.echo(click.style(step, fg="bright_black"))
        time.sleep(0.04)

def _print_ats_report(report: dict, verbose: bool):
    coverage = report["coverage_pct"]
    color = "green" if coverage >= 65 else "yellow" if coverage >= 45 else "red"
    click.echo(f"  ATS Keyword Coverage : {click.style(f'{coverage}%', fg=color, bold=True)}")
    if report["gap_keywords"]:
        click.echo(click.style("\n  ⚠  Gap Keywords (present in JD, missing from resume):", fg="yellow"))
        gaps = [f"{k} ({n}×)" for k, n in report["gap_keywords"][:8]]
        for g in gaps:
            click.echo(f"      • {g}")
        click.echo()
        click.echo(click.style("  💡 Keyword Injection Suggestions:", fg="cyan"))
        click.echo("     → Add gap keywords naturally to Summary or bullet points.")
        click.echo("     → Target: ≥65% keyword overlap for strong ATS scoring.")

    if verbose and report["present_keywords"]:
        click.echo(click.style("\n  ✓  Matched Keywords:", fg="green"))
        matched = [f"{k}" for k, _ in report["present_keywords"][:10]]
        click.echo("     " + "  •  ".join(matched))

def _print_summary_box(output_path: str, ats_report: dict | None):
    lines = [
        ("PDF", output_path),
        ("Layout", "Single-column · ATS-safe · Text-layer only"),
        ("Design", "Stitch Sovereign Executive v1 (Architectural Ledger)"),
    ]
    if ats_report:
        lines.append(("ATS Score", f"{ats_report['coverage_pct']}% keyword match"))
    click.echo(click.style("  ╔══ OUTPUT SUMMARY ", fg="green") + 
               click.style("═" * 26 + "╗", fg="green"))
    for k, v in lines:
        key = click.style(f"  ║  {k:<12}", fg="green")
        click.echo(f"{key}{v}")
    click.echo(click.style("  ╚" + "═" * 42 + "╝", fg="green"))
    click.echo()

if __name__ == "__main__":
    cli()